kind: Template
apiVersion: v1
labels:
  template: openshift-slack-notifications
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: go
  spec:
    tags:
    - from:
        kind: DockerImage
        name: jatescher/s2i-go:latest
      name: latest

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPLICATION_NAME}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/finderly/openshift-slack-notifications"
    strategy:
      type: Source
      sourceStrategy:
          from:
            kind: ImageStreamTag
            name: "go:latest"
          incremental: true
    output:
      to:
        kind: "ImageStreamTag"
        name: "${APPLICATION_NAME}:latest"

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}
    annotations:
      description: Openshift Slack Notifications
  spec:
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APPLICATION_NAME}
          from:
            kind: "ImageStreamTag"
            name: ${APPLICATION_NAME}:latest
    replicas: 1
    selector:
      name: ${APPLICATION_NAME}
    template:
      metadata:
        name: ${APPLICATION_NAME}
        labels:
          name: ${APPLICATION_NAME}
      spec:
        containers:
          - name: ${APPLICATION_NAME}
            env:
              - name: SLACK_WEBHOOK_URL
                value: ${SLACK_WEBHOOK_URL}
              - name: OPENSHIFT_CONSOLE_URL
                value: ${OPENSHIFT_CONSOLE_URL}
            image: ' '
            readinessProbe:
              tcpSocket:
                  port: 8080
              initialDelaySeconds: 60
              timeoutSeconds: 1
            stdin: true
            tty: true

parameters:
- description: The name of the environment
  displayName: Application name
  name: APPLICATION_NAME
  required: true
  value: openshift-slack-notifications
- description: Openshift console URL. E.g. http://company.com/console
  displayName: OpenShift Console URL
  name: OPENSHIFT_CONSOLE_URL
  required: true
- description: The slack webhook url that notifications will be sent to.
  displayName: Slack Webhook URL
  name: SLACK_WEBHOOK_URL
  required: true